import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const manifest = JSON.parse(fs.readFileSync("./manifest.json", "utf8"));
const bundledDependencyInventory = JSON.parse(
	fs.readFileSync("./third-party/bundled-dependencies.json", "utf8")
);
const bundledDependencySummary = bundledDependencyInventory.packages
	.map(({ name, version, license }) => `- ${name} ${version} (${license})`)
	.join("\n");

// Read target from tsconfig.json to keep esbuild and TS in sync
// Note: tsconfig.json may contain comments, so we'll strip them before parsing
const tsconfigContent = fs.readFileSync("./tsconfig.json", "utf8")
	.replace(/\/\*[\s\S]*?\*\//g, '') // Remove /* */ comments
	.replace(/\/\/.*$/gm, ''); // Remove // comments
const tsconfig = JSON.parse(tsconfigContent);
const tsTarget = (tsconfig?.compilerOptions?.target ?? "ES2020").toLowerCase();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Image Assistant Plugin v${manifest.version}
Source: https://github.com/RandyAllenEEE/obsidian-image-assistant

Third-party software included in this bundle:
- heic-to 1.0.2 (LGPL-3.0-only)
- UTIF.js revision 2e6be655cb1beee3b4fc193deefee35b10b3a68c (MIT)
${bundledDependencySummary}

Notices, license texts, corresponding-source links, and modification details:
https://github.com/RandyAllenEEE/obsidian-image-assistant/blob/main/THIRD_PARTY_NOTICES.md
Versioned notice/license/source assets: https://github.com/RandyAllenEEE/obsidian-image-assistant/releases
*/
`;

const prod = (process.argv[2] === "production");
const productionMetafiles = {};

const referenceIndexWorkerPlugin = {
	name: "reference-index-worker-source",
	setup(build) {
		build.onResolve({ filter: /^virtual:reference-index-worker$/ }, () => ({
			path: "reference-index-worker",
			namespace: "reference-index-worker"
		}));
		build.onLoad({
			filter: /.*/,
			namespace: "reference-index-worker"
		}, async () => {
			const nodeResult = await esbuild.build({
				entryPoints: ["./src/utils/reference-index/ReferenceIndexWorkerEntry.ts"],
				bundle: true,
				write: false,
				platform: "node",
				format: "cjs",
				target: tsTarget,
				tsconfig: "tsconfig.json",
				external: ["worker_threads"],
				minify: prod,
				metafile: true,
				logLevel: "silent"
			});
			const browserResult = await esbuild.build({
				entryPoints: ["./src/utils/reference-index/ReferenceIndexWebWorkerEntry.ts"],
				bundle: true,
				write: false,
				platform: "browser",
				format: "iife",
				target: tsTarget,
				tsconfig: "tsconfig.json",
				minify: prod,
				metafile: true,
				logLevel: "silent"
			});
			if (prod) {
				productionMetafiles.referenceIndexNode = nodeResult.metafile;
				productionMetafiles.referenceIndexBrowser = browserResult.metafile;
			}
			const nodeOutput = nodeResult.outputFiles?.[0]?.text;
			const browserOutput = browserResult.outputFiles?.[0]?.text;
			if (!nodeOutput || !browserOutput) {
				throw new Error("Reference index Worker bundle was empty");
			}
			return {
				contents: `export default ${JSON.stringify({
					browser: browserOutput,
					node: nodeOutput
				})};`,
				loader: "js",
				watchFiles: [...new Set([
					...Object.keys(nodeResult.metafile?.inputs ?? {}),
					...Object.keys(browserResult.metafile?.inputs ?? {})
				])]
			};
		});
	}
};

if (prod) {
	fs.rmSync("build", { recursive: true, force: true });
	fs.mkdirSync("build", { recursive: true });
}

// Build configuration optimized for Obsidian Image Assistant Plugin
const buildConfig = {
	banner: {
		js: banner,
	},
	entryPoints: ["./src/main.ts"],
	bundle: true,
	external: [
		// Obsidian and Electron APIs
		"obsidian",
		"electron",
		// CodeMirror (provided by Obsidian)
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// Node.js built-in modules
		...builtins,
	],
	format: "cjs",

	// Target derived from tsconfig.json
	target: tsTarget,

	logLevel: prod ? "error" : "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,

	// Minification strategy for production
	minify: prod,
	minifyWhitespace: prod,
	minifyIdentifiers: prod,
	minifySyntax: prod,

	// Debugging aids
	keepNames: !prod,

	// Production optimizations
	drop: prod ? ["debugger"] : [],

	outfile: "build/main.js",
	platform: "node",
	tsconfig: "tsconfig.json", // Make esbuild pick up paths and TS settings consistently

	// Required by UTIF.js library
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},

	metafile: prod,
	plugins: [referenceIndexWorkerPlugin],
};

// Helper function to copy files to build
async function copyToBuild() {
	// Ensure build directory exists
	if (!fs.existsSync('build')) {
		fs.mkdirSync('build', { recursive: true });
	}
	
	// Copy manifest.json
	if (fs.existsSync('manifest.json')) {
		fs.copyFileSync('manifest.json', 'build/manifest.json');
	}
	
	// Copy styles.css if it exists
	if (fs.existsSync('styles.css')) {
		fs.copyFileSync('styles.css', 'build/styles.css');
	}
}

// Create build context
const context = await esbuild.context(buildConfig);


if (prod) {
	try {
		console.log("\n🚀 Building Image Assistant Plugin...");
		console.log(`📌 Version: ${manifest.version}`);
		
		const result = await context.rebuild();
		productionMetafiles.main = result.metafile;
		fs.writeFileSync(
			"build/esbuild-metafile.json",
			`${JSON.stringify({
				formatVersion: 1,
				esbuildVersion: esbuild.version,
				production: true,
				bundles: productionMetafiles
			}, null, 2)}\n`,
			"utf8"
		);
		
		// Copy additional files to build
		await copyToBuild();
		
		console.log("✅ Production build completed in build/\n");
		
		await context.dispose();
		process.exit(0);
	} catch (error) {
		console.error("\n❌ Build failed:", error.message);
		await context.dispose();
		process.exit(1);
	}
} else {
	// Development mode with file watching
	try {
		await context.watch();
		
		// Copy files to build in dev mode too
		await copyToBuild();
		
		console.log("\n🖼️  Image Assistant Plugin - Development Mode");
		console.log("=".repeat(50));
		console.log("📌 Version:    " + manifest.version);
		console.log("🎯 Target:     " + tsTarget.toUpperCase());
		console.log("📁 Entry:      ./src/main.ts");
		console.log("📤 Output:     ./build/");
		console.log("\n👀 Watching for changes... (Ctrl+C to stop)\n");
		
		// Handle graceful shutdown
		process.on('SIGINT', async () => {
			console.log("\n🛑 Stopping development server...");
			await context.dispose();
			process.exit(0);
		});
	} catch (error) {
		console.error("❌ Failed to start development mode:", error);
		process.exit(1);
	}
}
